services:
  sgs-housing-bot:
    build: .
    restart: always
    secrets:
      - smtp_server
      - smtp_port
      - smtp_user
      - smtp_password
      - vasttrafik_api_key
    volumes:
      - ./data/sgs-housing-bot:/var/lib/sgs-housing-bot
    environment:
      - SMTP_SERVER_FILE=/run/secrets/smtp_server
      - SMTP_PORT_FILE=/run/secrets/smtp_port
      - SMTP_USER_FILE=/run/secrets/smtp_user
      - SMTP_PASSWORD_FILE=/run/secrets/smtp_password
      - VASTTRAFIK_API_KEY_FILE=/run/secrets/vasttrafik_api_key

secrets:
  smtp_server:
    file: ./data/secrets/smtp_server
  smtp_port:
    file: ./data/secrets/smtp_port
  smtp_user:
    file: ./data/secrets/smtp_user
  smtp_password:
    file: ./data/secrets/smtp_password
  vasttrafik_api_key:
    file: ./data/secrets/vasttrafik_api_key
